/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-arm"
#define TARGET_SHORT_ALIGNMENT 2
#define TARGET_INT_ALIGNMENT 4
#define TARGET_LONG_ALIGNMENT 4
#define TARGET_LLONG_ALIGNMENT 4
#define TARGET_ARCH "arm"
#define TARGET_ARM 1
#define TARGET_PHYS_ADDR_BITS 32
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_ARM_DIS 1
